### ISSUE TITLE
Input as a video?

### ISSUE THREAD

**Issue by raincrash** [georgeretsi/smirk#1]
Hello! 

Great work! 

Is there a way to input videos/track SMIRK over frames?

**Comment by filby89** [comment]
Hi,
thanks for your interest in smirk ! We just added a file called `demo_video.py` that can be used to run smirk on a video and render the results either in crop coordinate or in coordinates of the original video.

Let us know if everything works as intended.

**Comment by raincrash** [comment]
Works perfectly, thank you!
