### ISSUE TITLE
What FLAME version used in here?

### ISSUE THREAD

**Issue by yjhong89** [georgeretsi/smirk#10]
Hi! Thanks for sharing great work!

What FLAME version used in SMIRK??
- FLAME 2020 / general .pkl ?
- I am asking since advanced FLAME versions are updated in https://flame.is.tue.mpg.de/download.php
  - ![image](https://github.com/georgeretsi/smirk/assets/26890721/3a15c08b-1e51-4215-9cf3-155992ec865d)

- If I want to use FLAME 2023, need to re-train and re-adjust FLAME parameter corresponding 2023 version??

Thanks!

**Comment by filby89** [comment]
Hey,
yes smirk is using FLAME2020 / general .pkl.
If you want to use FLAME 2023 and you will need to change FLAME.py to load and use the corresponding blendshapes. I am not sure if FLAME 2023 uses the same shape parameters (in which case you need to retrain the shape encoder as well), but you definitely need to retrain the expression encoder.

**Comment by yjhong89** [comment]
Thank you!
