### ISSUE TITLE
mp landmark index

### ISSUE THREAD

**Issue by yjhong89** [georgeretsi/smirk#11]
Hi!

- Would you let me know each mediapipe 105 landmark represent  which part of face?
  - mediapipe landmarks return 105 landmark (https://github.com/georgeretsi/smirk/blob/b7c08bd6dc263c731c129b34e476c1f0814fcdbe/src/FLAME/FLAME.py#L314)
  - Like this figure.
  
     ![image](https://github.com/georgeretsi/smirk/assets/26890721/b83511a5-574d-4666-81a7-6ae5f2549664)

**Comment by filby89** [comment]
Hey, I think you can easily create this figure by plotting the mp landmarks using the demo file. We will add as soon as possible this figure as well.
