### ISSUE TITLE
pre-trained models

### ISSUE THREAD

**Issue by weimengting** [georgeretsi/smirk#12]
Hi, will you release the pre-trained weights of smirk?

**Comment by filby89** [comment]
Hey, the command 

```bash
bash quick_install.sh
``` 

also downloads the pretrained model. I have tweaked the readme to also explain this. You can find it here:

https://drive.google.com/file/d/1T65uEd9dVLHgVw5KiUYL66NUee-MCzoE/view?usp=sharing
