### ISSUE TITLE
Different jaw-pose FLAME parameter

### ISSUE THREAD

**Issue by airpdev** [georgeretsi/smirk#16]
Hello, everybody.
I have got jaw_pose parameter using smirk.
([[[ 0.0809, -0.0012, -0.0506]]], device='cuda:0')

But jaw_pose in metrical_tacker has different format.
([[1., 0., 0., 0., 1., 0.]], device='cuda:0', requires_grad=True)

Would you like to let me know which format is correct and how to convert with each other?
Thanks

**Comment by filby89** [comment]
Hi, we don't know the format of the metrical tracker. Can you point us to a file in their repo/demo ?

**Comment by airpdev** [comment]
Hello, thanks for your message.
https://github.com/Zielon/metrical-tracker/blob/c2a517244759d7eeaa0e84893d6748e75293f81a/tracker.py#L575
I was trying to replace jaw_pose. But the format is different.
I am very interested in smirk.
And I have tried to test smirk_generator and uploaded testing result.
We can generate image with different poses?
Thanks a lot.
![test_image2](https://github.com/user-attachments/assets/9f772299-749d-4021-ad7d-5ec3550a5e73)
