### ISSUE TITLE
Customizing mask.

### ISSUE THREAD

**Issue by airpdev** [georgeretsi/smirk#17]
Hello, would you like to let me know how to create mask to reconstruct only mouth area not full face?
In addition to this we can reconstruct lips part with different jaw pose?
Looking forward to hearing from you!
Thanks

**Comment by georgeretsi** [comment]
Hello! you can mask out only the mouth if you want to focus on the lips. You can do this with the mouth landmarks (e.g. from mediapipe) and select either a bounding box around it or a dilated convex hull. This way you will force the encoder to focus only on the mouth. If you use a different jaw pose, the current pipeline supports this fully. The transfer_pixel function translates the sampled lip pixels into their new position. Then the generator can form the lips. The only thing to keep in mind here is that you should also change the mask-out region. If, for example, you seek to open the mouth more, the mask-out region should be larger. This is supported right now for the full face with the _rendered_mask_ argument of the _masking_utils.masking_ function and can be modified to your needs.

**Comment by airpdev** [comment]
Thanks for your message.
I will check it and let you know the problems.
Thanks a lot.
