### ISSUE TITLE
Adding a Tracker to SMIRK

### ISSUE THREAD

**Issue by raincrash** [georgeretsi/smirk#2]
Since the pre-training is based on MICA, Is there a way to use Metrical_Tracker that comes with MICA, with SMIRK? 

If there is no direct way and need a bit of development effort, I am happy to do it and send a PR. Just need directions on how to go about it.

**Comment by filby89** [comment]
Hey, thanks for your interest in SMIRK ! 
If I'm not mistaken in https://github.com/Zielon/metrical-tracker/ MICA predictions are used to regularize shape throughout the iterative fitting. The most straightforward way to incorporate SMIRK here then would be to regularize w.r.t. SMIRK expression params as well.

Nonetheless,  I think that the SMIRK framework could probably work very nicely in an iterative fitting process with the cycle path as well, although we did not have the time to fully explore that yet.

Feel free to check both options and let us know on the results :) However, I think this is not in the scope of this repo and would probably better exist in its own repository.

**Comment by raincrash** [comment]
Thank you for the response! I will close the issue. Will also try to work on this, if something interesting comes up, I will post here for completeness.

**Comment by emlcpfx** [comment]
Is there a way to use the identity.npy file that MICA makes in order to make the face fit even better?

**Comment by andfoy** [comment]
@raincrash did you ever managed to integrate SMIRK into a tracker?
