### ISSUE TITLE
Any solution to improve the quality of lipsyncronized video?

### ISSUE THREAD

**Issue by airpdev** [georgeretsi/smirk#21]
Hello, I have generated lipsync video from video and audio using smirk and other models.

https://github.com/user-attachments/assets/acdeeeaf-116f-4699-a7e0-259036b013bd

Video as input:

https://github.com/user-attachments/assets/a4fe31a3-0f85-45ef-abed-3c700646fe5d

**Comment by jeb0813** [comment]
Hi @airpdev , is the first video generated by smirk? I tried on input video you provided, but the output vid has much flickering. Did you add extra steps or other models?

Thank you!

**Comment by filby89** [comment]
Hi, the smirk generator is not temporally stable and not trained to do so, so what you are seeing is normal (the generator is a byproduct of our training of the encoder). 
One solution to obtain results would be to train a personalized generator on only a person and video, keeping the encoder frozen. Some relevant resources:

https://foivospar.github.io/NED/
https://github.com/michaildoukas/head2head
