### ISSUE TITLE
Smoothing Data for Video

### ISSUE THREAD

**Issue by emlcpfx** [georgeretsi/smirk#23]
Do you think there would be a benefit to adding a smoothing algorithm that looks at the previous and next frames, and blends the results between them? Or do you think it would be more accurate to take it one frame at a time, as is?

**Comment by emlcpfx** [comment]
Closing this: I wrote a thing that smooths and filters the landmarks coming out of retinaface (which i swapped in for mediapipe,) and feeds that into SMIRK after processing all the landmarks. It's good!

**Comment by xuduo18311199384** [comment]
How to perform data smoothing? Is it smoothing for 768 landmarks？

**Comment by emlcpfx** [comment]
I’m in the middle of a job right now, but I can upload code in a month or so.

**Comment by xuduo18311199384** [comment]
Have you successfully smoothed the reconstruction result？Can you tell me how to operate it specifically？ 
@emlcpfx

**Comment by emlcpfx** [comment]
Yes. You need to do all of the SMIRK encoding before rendering anything. Once you have all of the encoded info stored, you can run it through filters like median and savgol, and then pass that to the renderer.
