### ISSUE TITLE
The link is missing... https://drive.google.com/file/d/1wEL7KPHw2kl5DxP0UAB3h9QcQLXk7BM_

### ISSUE THREAD

**Issue by xuduo18311199384** [georgeretsi/smirk#27]

**Comment by filby89** [comment]
Hey, I can successfully access the link here:

[https://drive.google.com/file/d/1wEL7KPHw2kl5DxP0UAB3h9QcQLXk7BM_](https://drive.google.com/file/d/1wEL7KPHw2kl5DxP0UAB3h9QcQLXk7BM_)

what are you doing exactly ?
