### ISSUE TITLE
How to reproduce results on AffectNet?

### ISSUE THREAD

**Issue by nlml** [georgeretsi/smirk#30]
Hello,

Thanks for this great work!

Would you be able to release a script showing how to reproduce the results you present in Table 1 of the paper?

Or could you provide details on how to obtain this result?

Thanks!
Liam

**Comment by filby89** [comment]
Hey @nlml thanks for your interest in smirk ! The protocol is taken from EMOCA https://emoca.is.tue.mpg.de but I believe it is not publicly available.
For more information you can contact via e-mail to https://ps.is.mpg.de/person/rdanecek.
