### ISSUE TITLE
Can a fixed value be used for the camera CAM parameter here?

### ISSUE THREAD

**Issue by zckcola** [georgeretsi/smirk#4]
Here are the obtained pose and cam. Does the cam here refer to the camera parameters? Is it possible to select a camera parameter with a front-facing orientation?
![image](https://github.com/georgeretsi/smirk/assets/145427194/2834ef77-b635-4fee-97fb-1b23b7461c13)
Can the following be made to face forward?
![image](https://github.com/georgeretsi/smirk/assets/145427194/18722991-688e-48a3-a8aa-95c3781c77d9)
hope you can answer my question, thank you.

**Comment by filby89** [comment]
Hey the pose of the head w.r.t. camera is controlled by the pose parameters, so if you set the pose_params vector to zero you will get a front facing face!

**Comment by zckcola** [comment]
> 嘿，头部的姿势由姿势参数控制，所以如果你将pose_params矢量设置为零，你会得到一个正面的脸！

那请问cam参数控制的的不是相机矢量吗

**Comment by zckcola** [comment]
> 嘿，头部的姿势由姿势参数控制，所以如果你将pose_params矢量设置为零，你会得到一个正面的脸！

很高兴您能回答我的问题，pose是控制人脸脸部朝向，shape是控制形状大小？eye是眼部，jaw是上下颚，exp是控制表情。对吗？

**Comment by zckcola** [comment]
> 嘿，头部的姿势由姿势参数控制，所以如果你将pose_params矢量设置为零，你会得到一个正面的脸！

 I’m glad you could answer my question. Pose controls the orientation of the face, shape controls the size and shape, eye refers to the eyes, jaw refers to the upper and lower jaws, and exp controls the expression. Is that right?

**Comment by filby89** [comment]
Hi, yes these are correct. Note that jaw is only controlling the lower jaw joint and the eye params control the left/right eyelid opening/closing.
You can check more info in https://flame.is.tue.mpg.de.

**Comment by zckcola** [comment]
> Hi, yes these are correct. Note that jaw is only controlling the lower jaw joint and the eye params control the left/right eyelid opening/closing. You can check more info in https://flame.is.tue.mpg.de.

thanks！
