### ISSUE TITLE
Can I obtain the mesh files?

### ISSUE THREAD

**Issue by GrizzCMX** [georgeretsi/smirk#9]
The current results exist as monochromatic rendered mesh images. How can I directly obtain the mesh source files, for instance, stored in a common 3D file format like OBJ or others? Additionally, the paper mentions using FLAME as the facial prior, but the results do not appear to have FLAME topology. Is additional post-processing required?

**Comment by raincrash** [comment]
The flame param outputs are stored [here](https://github.com/georgeretsi/smirk/blob/b7c08bd6dc263c731c129b34e476c1f0814fcdbe/demo_video.py#L141), for example, and you can use them to create a mesh.

**Comment by GrizzCMX** [comment]
> The flame param outputs are stored [here](https://github.com/georgeretsi/smirk/blob/b7c08bd6dc263c731c129b34e476c1f0814fcdbe/demo_video.py#L141), for example, and you can use them to create a mesh.

Thanks for your reply
